playwright:
  env:

browser:
  # chromium, firefox, webkit
  name: chromium
  # "chrome", "chrome-beta", "chrome-dev", "chrome-canary", "msedge", "msedge-beta", "msedge-dev", or "msedge-canary"
  channel: msedge
  headless: false
  timeout: 30000
  slowMo: 0
  devtools: false
  websocketEndpoint:
  screenshotDir: "./screenshots"
  viewport:
    width: 1920
    height: 1080

api:
  headers:
    Content-type: application/json
  
  timeout: 30000
  maxRedirects: 5
  maxRetries: 0

app:
  baseUrl: "https://the-internet.herokuapp.com"
  timeout: 30000

test:
  parallel: true
  threads: 4
  retries: 2
  screenshots: true
  videos: false
  traces: true

logging:
  level: DEBUG
  enablePerformance: true
  enableAPIDebug: true

allure:
  resultsDirectory: "allure-results"